### ISSUE TITLE
Crash during directory selection (Windows)

### ISSUE THREAD

**Issue by JonathanHarford** [bcpierce00/unison#21]
Unison 2.48.3
Windows 10 64-bit

When setting up a new profile and slecting the first directory to sync, Unison crashes. Console says:

`(unison 2.48.3 GTK.exe:1992): Gtk-CRITICAL **: gtk_tree_model_filter_get_value: assertion 'GTK_TREE_MODEL_FILTER (model)->priv->stamp == iter->stamp' failed`

**Comment by bcpierce00** [comment]
This needs a Windows / GTK expert to look at it.

**Comment by PeterMosmans** [comment]
Hi @JonathanHarford - Did you compile Unison yourself ? If so, with which parameters ? And what GTK+ runtime version do you use ?

Thanks in advance,

Peter

**Comment by JonathanHarford** [comment]
I installed the precompiled binary.

**Comment by PeterMosmans** [comment]
And, which one @JonathanHarford ? From https://www.irif.univ-paris-diderot.fr/~vouillon/unison/ ? That one lists 2.48.4 : same issue ?
Which GTK+ runtime version do you use ? 64 bit, I presume :wink: ?

**Comment by JonathanHarford** [comment]
I couldn't tell you for certain, as I uninstalled it when I couldn't get it
to work. I suspect the GTK version would be whichever came in the installer.

**Comment by PeterMosmans** [comment]
Hi,

I built the latest version from the master branch (2.50.0) on Windows 10 64 bit (x86_64 Msys2), using OCaml 4.02.3, runtime GTK+ 2.24.10 and library files 2.24.28. I can't reproduce the isssue.
As the original poster @JonathanHarford doesn't have much more information, I suggest to close this issue @bcpierce00

**Comment by bcpierce00** [comment]
Done

**Comment by tayl0r** [comment]
The crash still happens from the precompiled binaries available from https://www.irif.fr/~vouillon/unison/ (linked from the official Unison site). I tried the last 5 versions (including the 2.5 beta) and each one has the crash. Perhaps those need to be updated with your binary @PeterMosmans ?

**Comment by PeterMosmans** [comment]
Hi @tayl0r - do you by any chance have e.g. Pidgin or GIMP installed ? Those have the GTK2+ runtime bundled. What I could do as first step is pass you a 'fresh' GTK2+ environment (DLLs) - if you could add those to the same directory as where you're starting Unison from and see whether it works then. Do you use the 32-bit or 64-bit version of Unison ? Of course I can also send you a ZIPped file containing the runtime libs as well as the executable.

**Comment by tayl0r** [comment]
I actually was able to test that idea myself. I installed https://sourceforge.net/projects/gtk-win/ and then copied "libgtk-win32-2.0-0.dll" (from the "C:\Program Files (x86)\GTK2-Runtime\bin" folder) into the unison folder. Viola, no more crash. But, the GUI does look uglier =P

The binaries are only available in 1 version and I'm not sure if it is 64 or 32 bit because it doesn't say. But it seems like it is the 32 bit version because the GTK lib is the 32 bit version, and they have to match up, right?

So yeah, maybe you guys should bundle that DLL with the windows binaries? I'm not sure what the proper solution would be. At least now other people with the crash can do this work around. I'm pretty sure I don't have any other GTK libs installed, but of course I could be wrong.

You can see the difference in the GUI with the different GTK libs in these 2 screenshots:
Working (new DLL): http://screencast.com/t/zxymM6grEuJ
Not working (default): http://screencast.com/t/iLj0PZrV1F8

**Comment by PeterMosmans** [comment]
Hi @tayl0r - I finally managed to reproduce your issue under a strict 64-bit environment: When compiling the latest 64-bit Unison version on mingw64, using gcc 6.2.0, ocaml 4.02.3, gtk2 runtime 2.24.31-1 and  lablgtk 2.18.5, the application segfaults when selecting a directory. @bcpierce00 - could you reopen this issue ? Thanks !

**Comment by bcpierce00** [comment]
Done!

**Comment by PeterMosmans** [comment]
Thanks @bcpierce00 - So far I traced the error back to
```
(unison.exe:14996): GLib-GIO- CRITICAL **: GetVolumePathName failed: Incorrect function.
```

**Comment by gdt** [comment]
Could the people who have the issue retest with 2.51.2 or git master?

**Comment by tleedjarv** [comment]
I think this issue can be closed. GTK+ DLLs are packaged with releases published on GitHub now. I did a quick test with a 32-bit and a 64-bit package and could not trigger this issue.
